name: cartpole-pytorch-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - gymnasium
  - pygame
  - matplotlib
  - opencv 
  - pip
  - pip:
      - -r requirements.txt
